# Generated by Django on 2026-08-17

from django.db import migrations


def seed_jps2_company(apps, schema_editor):
    Company = apps.get_model('settings', 'Company')
    User = apps.get_model('users', 'User')
    Role = apps.get_model('users', 'Role')
    DriverCommission = apps.get_model('users', 'DriverCommission')
    Customer = apps.get_model('customers', 'Customer')
    CreditLine = apps.get_model('customers', 'CreditLine')
    CreditPayment = apps.get_model('customers', 'CreditPayment')
    BorrowedContainer = apps.get_model('customers', 'BorrowedContainer')
    Product = apps.get_model('core', 'Product')
    SystemConfig = apps.get_model('core', 'SystemConfig')
    Remittance = apps.get_model('remittance', 'Remittance')
    RemittanceRider = apps.get_model('remittance', 'RemittanceRider')
    RemittanceRiderProductLine = apps.get_model('remittance', 'RemittanceRiderProductLine')
    Expense = apps.get_model('remittance', 'Expense')
    RiderCredit = apps.get_model('remittance', 'RiderCredit')
    RiderCreditRepayment = apps.get_model('remittance', 'RiderCreditRepayment')
    RiderDeduction = apps.get_model('remittance', 'RiderDeduction')
    RemittanceStaff = apps.get_model('remittance', 'RemittanceStaff')
    StaffDeduction = apps.get_model('remittance', 'StaffDeduction')

    company, _ = Company.objects.get_or_create(
        name='JPS 2',
        defaults={
            'address': 'Sitio Talaba, San Jacinto, Masbate',
            'contact_number': '+63 912 345 6789',
            'email': 'jps2@hydr8.ph',
        }
    )

    # Backfill company on users, roles, products, system configs, customers
    User.objects.filter(company__isnull=True).update(company=company)
    Role.objects.filter(company__isnull=True).update(company=company)
    DriverCommission.objects.filter(company__isnull=True).update(company=company)
    Customer.objects.filter(company__isnull=True).update(company=company)
    CreditLine.objects.filter(company__isnull=True).update(company=company)
    CreditPayment.objects.filter(company__isnull=True).update(company=company)
    BorrowedContainer.objects.filter(company__isnull=True).update(company=company)
    Product.objects.filter(company__isnull=True).update(company=company)
    SystemConfig.objects.filter(company__isnull=True).update(company=company)

    # Temporarily drop application triggers so historical finalized rows can be backfilled
    # with company_id without triggering immutability exceptions (works without superuser)
    is_postgres = schema_editor.connection.vendor == 'postgresql'
    if is_postgres:
        schema_editor.execute("DROP TRIGGER IF EXISTS trg_lock_finalized_remittance ON remittance_remittance;")
        schema_editor.execute("DROP TRIGGER IF EXISTS trg_guard_finalized_rider ON remittance_remittance_rider;")
        schema_editor.execute("DROP TRIGGER IF EXISTS trg_guard_finalized_product_line ON remittance_remittance_rider_productline;")
        schema_editor.execute("DROP TRIGGER IF EXISTS trg_guard_finalized_expense ON remittance_expense;")

    try:
        # For remittances: assign company to 1 remittance per date (to satisfy UNIQUE (company, date))
        # preserving any duplicate drafts intact with company=NULL
        assigned_remittance_ids = set()
        for rem in Remittance.objects.filter(company__isnull=True).order_by('date', '-id'):
            if rem.date not in {r.date for r in Remittance.objects.filter(id__in=assigned_remittance_ids)}:
                rem.company = company
                rem.save(update_fields=['company'])
                assigned_remittance_ids.add(rem.id)

        # For child remittance tables, assign company matching parent remittance
        for rem_id in assigned_remittance_ids:
            RemittanceRider.objects.filter(remittance_id=rem_id, company__isnull=True).update(company=company)
            RemittanceRiderProductLine.objects.filter(remittance_rider__remittance_id=rem_id, company__isnull=True).update(company=company)
            Expense.objects.filter(remittance_id=rem_id, company__isnull=True).update(company=company)
            RiderCredit.objects.filter(company__isnull=True).update(company=company)
            RiderCreditRepayment.objects.filter(remittance_id=rem_id, company__isnull=True).update(company=company)
            RiderDeduction.objects.filter(remittance_rider__remittance_id=rem_id, company__isnull=True).update(company=company)
            RemittanceStaff.objects.filter(remittance_id=rem_id, company__isnull=True).update(company=company)
            StaffDeduction.objects.filter(remittance_staff__remittance_id=rem_id, company__isnull=True).update(company=company)
    finally:
        if is_postgres:
            schema_editor.execute("""
                DROP TRIGGER IF EXISTS trg_lock_finalized_remittance ON remittance_remittance;
                CREATE TRIGGER trg_lock_finalized_remittance
                BEFORE UPDATE OR DELETE ON remittance_remittance
                FOR EACH ROW
                EXECUTE FUNCTION fn_lock_finalized_remittance();

                DROP TRIGGER IF EXISTS trg_guard_finalized_rider ON remittance_remittance_rider;
                CREATE TRIGGER trg_guard_finalized_rider
                BEFORE INSERT OR UPDATE OR DELETE ON remittance_remittance_rider
                FOR EACH ROW
                EXECUTE FUNCTION fn_guard_remittance_child();

                DROP TRIGGER IF EXISTS trg_guard_finalized_product_line ON remittance_remittance_rider_productline;
                CREATE TRIGGER trg_guard_finalized_product_line
                BEFORE INSERT OR UPDATE OR DELETE ON remittance_remittance_rider_productline
                FOR EACH ROW
                EXECUTE FUNCTION fn_guard_remittance_child();

                DROP TRIGGER IF EXISTS trg_guard_finalized_expense ON remittance_expense;
                CREATE TRIGGER trg_guard_finalized_expense
                BEFORE INSERT OR UPDATE OR DELETE ON remittance_expense
                FOR EACH ROW
                EXECUTE FUNCTION fn_guard_remittance_child();
            """)


def reverse_seed_jps2_company(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_company_options'),
        ('users', '0008_default_roles_and_permissions'),
        # Must include 0009 (not just 0001) because the RunPython
        # operation below references BorrowedContainer, which is created
        # in customers.0009_borrowed_container_and_creditline_care_of.
        ('customers', '0009_borrowed_container_and_creditline_care_of'),
        ('core', '0001_initial'),
        ('remittance', '0012_alter_expense_options_alter_remittance_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_jps2_company, reverse_seed_jps2_company),
    ]
