# Generated by Django 6.0.7 on 2026-07-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'remittance_expense',
            },
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_credit_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_borrowed_items', models.SmallIntegerField(default=0)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tithe_rate_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('tithe_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('offering_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tithes_paid', models.BooleanField(default=False)),
                ('offering_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'remittance_remittance',
            },
        ),
        migrations.CreateModel(
            name='RemittanceRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('subtotal_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'remittance_remittancerider',
            },
        ),
        migrations.CreateModel(
            name='RemittanceRiderProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_sold', models.SmallIntegerField()),
                ('qty_credited', models.SmallIntegerField(default=0)),
                ('borrowed_items', models.SmallIntegerField(default=0)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate_snapshot', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'remittance_remittanceriderproductline',
            },
        ),
    ]
