# Generated by Django 6.0.7 on 2026-08-01 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('customers', '0003_initial'),
        ('remittance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remittance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_remittances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remittance',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_remittances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='remittance.remittance'),
        ),
        migrations.AddField(
            model_name='remittancerider',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='remittance.remittance'),
        ),
        migrations.AddField(
            model_name='remittancerider',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remittanceriderproductline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_lines', to='core.product'),
        ),
        migrations.AddField(
            model_name='remittanceriderproductline',
            name='remittance_rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='remittance.remittancerider'),
        ),
        migrations.AddField(
            model_name='ridercredit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_credits', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='ridercredit',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_rider_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridercredit',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridercreditrepayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_repayments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridercreditrepayment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_repayments', to='remittance.remittance'),
        ),
        migrations.AddField(
            model_name='ridercreditrepayment',
            name='rider_credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='remittance.ridercredit'),
        ),
        migrations.AddIndex(
            model_name='remittance',
            index=models.Index(fields=['status'], name='remittance__status_feb3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='remittance',
            index=models.Index(fields=['tithes_paid', 'offering_paid'], name='remittance__tithes__5cb404_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['remittance'], name='remittance__remitta_2c0d46_idx'),
        ),
        migrations.AddIndex(
            model_name='remittancerider',
            index=models.Index(fields=['remittance'], name='remittance__remitta_6fe674_idx'),
        ),
        migrations.AddIndex(
            model_name='remittancerider',
            index=models.Index(fields=['rider'], name='remittance__rider_i_822c84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='remittancerider',
            unique_together={('remittance', 'rider')},
        ),
        migrations.AddIndex(
            model_name='remittanceriderproductline',
            index=models.Index(fields=['remittance_rider'], name='remittance__remitta_254969_idx'),
        ),
        migrations.AddIndex(
            model_name='remittanceriderproductline',
            index=models.Index(fields=['product'], name='remittance__product_0dc404_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='remittanceriderproductline',
            unique_together={('remittance_rider', 'product')},
        ),
        migrations.AddIndex(
            model_name='ridercredit',
            index=models.Index(fields=['rider'], name='remittance__rider_i_86c27e_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercredit',
            index=models.Index(fields=['is_repaid'], name='remittance__is_repa_389083_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercredit',
            index=models.Index(fields=['created_at'], name='remittance__created_306262_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercreditrepayment',
            index=models.Index(fields=['rider_credit'], name='remittance__rider_c_901fef_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercreditrepayment',
            index=models.Index(fields=['remittance'], name='remittance__remitta_08e699_idx'),
        ),
    ]
