# Generated by Django 6.0.7 on 2026-07-31 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_initial'),
        ('remittance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='total_repayments_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='remittance',
            name='total_rider_credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='RiderCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate_snapshot', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_repaid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_credits', to='customers.customer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_rider_credits', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remittance_ridercredit',
            },
        ),
        migrations.CreateModel(
            name='RiderCreditRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_repaid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_repayments', to=settings.AUTH_USER_MODEL)),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_repayments', to='remittance.remittance')),
                ('rider_credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='remittance.ridercredit')),
            ],
            options={
                'db_table': 'remittance_ridercreditrepayment',
            },
        ),
        migrations.AddIndex(
            model_name='ridercredit',
            index=models.Index(fields=['rider'], name='remittance__rider_i_86c27e_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercredit',
            index=models.Index(fields=['is_repaid'], name='remittance__is_repa_389083_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercredit',
            index=models.Index(fields=['created_at'], name='remittance__created_306262_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercreditrepayment',
            index=models.Index(fields=['rider_credit'], name='remittance__rider_c_901fef_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercreditrepayment',
            index=models.Index(fields=['remittance'], name='remittance__remitta_08e699_idx'),
        ),
    ]
