# Generated by Django 6.0.7 on 2026-08-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='remittancerider',
            new_name='remittance__remitta_a1d3f2_idx',
            old_name='remittance__remitta_6fe674_idx',
        ),
        migrations.RenameIndex(
            model_name='remittancerider',
            new_name='remittance__rider_i_fa92e5_idx',
            old_name='remittance__rider_i_822c84_idx',
        ),
        migrations.RenameIndex(
            model_name='remittanceriderproductline',
            new_name='remittance__remitta_1e532d_idx',
            old_name='remittance__remitta_254969_idx',
        ),
        migrations.RenameIndex(
            model_name='remittanceriderproductline',
            new_name='remittance__product_ca1dfb_idx',
            old_name='remittance__product_0dc404_idx',
        ),
        migrations.RenameIndex(
            model_name='ridercredit',
            new_name='remittance__rider_i_53e8cb_idx',
            old_name='remittance__rider_i_86c27e_idx',
        ),
        migrations.RenameIndex(
            model_name='ridercredit',
            new_name='remittance__is_repa_7669be_idx',
            old_name='remittance__is_repa_389083_idx',
        ),
        migrations.RenameIndex(
            model_name='ridercredit',
            new_name='remittance__created_0603bf_idx',
            old_name='remittance__created_306262_idx',
        ),
        migrations.RenameIndex(
            model_name='ridercreditrepayment',
            new_name='remittance__rider_c_a292dc_idx',
            old_name='remittance__rider_c_901fef_idx',
        ),
        migrations.RenameIndex(
            model_name='ridercreditrepayment',
            new_name='remittance__remitta_f0edaf_idx',
            old_name='remittance__remitta_08e699_idx',
        ),
        migrations.AlterModelTable(
            name='remittancerider',
            table='remittance_remittance_rider',
        ),
        migrations.AlterModelTable(
            name='remittanceriderproductline',
            table='remittance_remittance_rider_productline',
        ),
        migrations.AlterModelTable(
            name='ridercredit',
            table='remittance_rider_credit',
        ),
        migrations.AlterModelTable(
            name='ridercreditrepayment',
            table='remittance_rider_credit_repayment',
        ),
    ]
