# Generated by Django 6.0.7 on 2026-08-12 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_unique_together_product_category_and_more'),
        ('customers', '0007_remove_creditpayment_customers_c_credit__50d466_idx_and_more'),
        ('remittance', '0003_rename_remittance__remitta_6fe674_idx_remittance__remitta_a1d3f2_idx_and_more'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='remittance__remitta_2c0d46_idx',
        ),
        migrations.RemoveIndex(
            model_name='remittance',
            name='remittance__status_feb3e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='remittance',
            name='remittance__tithes__5cb404_idx',
        ),
        migrations.RemoveIndex(
            model_name='remittancerider',
            name='remittance__remitta_a1d3f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='remittancerider',
            name='remittance__rider_i_fa92e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='remittanceriderproductline',
            name='remittance__remitta_1e532d_idx',
        ),
        migrations.RemoveIndex(
            model_name='remittanceriderproductline',
            name='remittance__product_ca1dfb_idx',
        ),
        migrations.RemoveIndex(
            model_name='ridercredit',
            name='remittance__rider_i_53e8cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='ridercredit',
            name='remittance__is_repa_7669be_idx',
        ),
        migrations.RemoveIndex(
            model_name='ridercredit',
            name='remittance__created_0603bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='ridercreditrepayment',
            name='remittance__rider_c_a292dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='ridercreditrepayment',
            name='remittance__remitta_f0edaf_idx',
        ),
        migrations.AlterUniqueTogether(
            name='remittancerider',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='remittanceriderproductline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='settings.company'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='settings.company'),
        ),
        migrations.AddField(
            model_name='remittancerider',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_riders', to='settings.company'),
        ),
        migrations.AddField(
            model_name='remittanceriderproductline',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_rider_product_lines', to='settings.company'),
        ),
        migrations.AddField(
            model_name='ridercredit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_credits', to='settings.company'),
        ),
        migrations.AddField(
            model_name='ridercreditrepayment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_credit_repayments', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'remittance'], name='remittance__company_58a2cd_idx'),
        ),
        migrations.AddIndex(
            model_name='remittance',
            index=models.Index(fields=['company', 'status'], name='remittance__company_2ae37e_idx'),
        ),
        migrations.AddIndex(
            model_name='remittance',
            index=models.Index(fields=['company', 'tithes_paid', 'offering_paid'], name='remittance__company_fb6a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='remittancerider',
            index=models.Index(fields=['company', 'remittance'], name='remittance__company_ae7556_idx'),
        ),
        migrations.AddIndex(
            model_name='remittancerider',
            index=models.Index(fields=['company', 'rider'], name='remittance__company_3a35d5_idx'),
        ),
        migrations.AddIndex(
            model_name='remittanceriderproductline',
            index=models.Index(fields=['company', 'remittance_rider'], name='remittance__company_cb71fe_idx'),
        ),
        migrations.AddIndex(
            model_name='remittanceriderproductline',
            index=models.Index(fields=['company', 'product'], name='remittance__company_8abd72_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercredit',
            index=models.Index(fields=['company', 'rider'], name='remittance__company_83b302_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercredit',
            index=models.Index(fields=['company', 'is_repaid'], name='remittance__company_2297d3_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercredit',
            index=models.Index(fields=['company', 'created_at'], name='remittance__company_f848bd_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercreditrepayment',
            index=models.Index(fields=['company', 'rider_credit'], name='remittance__company_ac06ae_idx'),
        ),
        migrations.AddIndex(
            model_name='ridercreditrepayment',
            index=models.Index(fields=['company', 'remittance'], name='remittance__company_a564ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='remittance',
            constraint=models.UniqueConstraint(fields=('company', 'date'), name='unique_remittance_company_date'),
        ),
        migrations.AddConstraint(
            model_name='remittancerider',
            constraint=models.UniqueConstraint(fields=('company', 'remittance', 'rider'), name='unique_rr_company_remittance_rider'),
        ),
        migrations.AddConstraint(
            model_name='remittanceriderproductline',
            constraint=models.UniqueConstraint(fields=('company', 'remittance_rider', 'product'), name='unique_rrpl_company_rr_product'),
        ),
    ]
