# Generated by Django 6.0.7 on 2026-08-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0005_lock_finalized_remittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
