# Generated by Django 6.0.7 on 2026-08-14 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0006_add_total_salary_field'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate_snapshot', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('salary_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'remittance_remittance_staff',
            },
        ),
        migrations.CreateModel(
            name='RiderDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'remittance_rider_deduction',
            },
        ),
        migrations.CreateModel(
            name='StaffDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'remittance_staff_deduction',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='remittance_rider',
            field=models.ForeignKey(blank=True, help_text='When set, this expense is attributed to a specific rider.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='remittance.remittancerider'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='net_remittance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='remittance',
            name='total_other_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'remittance_rider'], name='remittance__company_205023_idx'),
        ),
        migrations.AddField(
            model_name='remittancestaff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_staff', to='settings.company'),
        ),
        migrations.AddField(
            model_name='remittancestaff',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payments', to='remittance.remittance'),
        ),
        migrations.AddField(
            model_name='remittancestaff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_staff_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderdeduction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_deductions', to='settings.company'),
        ),
        migrations.AddField(
            model_name='riderdeduction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_rider_deductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderdeduction',
            name='remittance_rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='remittance.remittancerider'),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_deductions', to='settings.company'),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_staff_deductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffdeduction',
            name='remittance_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='remittance.remittancestaff'),
        ),
        migrations.AddIndex(
            model_name='remittancestaff',
            index=models.Index(fields=['company', 'remittance'], name='remittance__company_f089e7_idx'),
        ),
        migrations.AddIndex(
            model_name='remittancestaff',
            index=models.Index(fields=['company', 'staff'], name='remittance__company_fa77d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='remittancestaff',
            constraint=models.UniqueConstraint(fields=('company', 'remittance', 'staff'), name='unique_rs_company_remittance_staff'),
        ),
        migrations.AddIndex(
            model_name='riderdeduction',
            index=models.Index(fields=['company', 'remittance_rider'], name='remittance__company_bc5ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='staffdeduction',
            index=models.Index(fields=['company', 'remittance_staff'], name='remittance__company_f6a5c9_idx'),
        ),
    ]
