# Generated by Django 6.0.7 on 2026-08-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0007_add_staff_rider_deductions_other_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittancerider',
            name='commission_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
