# Generated by Django 6.0.7 on 2026-08-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0009_remove_total_rider_credits_update_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittancerider',
            name='remitted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
