# Generated by Django 6.0.7 on 2026-08-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('remittance', '0010_remittancerider_remitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remittance',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ridercredit',
            name='notes',
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION fn_lock_finalized_remittance()
            RETURNS TRIGGER AS $$
            BEGIN
                IF OLD.status = 'FINALIZED' THEN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION
                            'remittance id=% is FINALIZED and cannot be deleted',
                            OLD.id;
                    END IF;

                    IF NEW.status <> 'FINALIZED' THEN
                        RAISE EXCEPTION
                            'remittance id=% is FINALIZED; status cannot be reverted',
                            OLD.id;
                    END IF;

                    IF NEW.date IS DISTINCT FROM OLD.date
                        OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
                        OR NEW.finalized_by_id IS DISTINCT FROM OLD.finalized_by_id
                        OR NEW.total_sales IS DISTINCT FROM OLD.total_sales
                        OR NEW.total_credit_sales IS DISTINCT FROM OLD.total_credit_sales
                        OR NEW.total_commission IS DISTINCT FROM OLD.total_commission
                        OR NEW.total_salary IS DISTINCT FROM OLD.total_salary
                        OR NEW.total_expenses IS DISTINCT FROM OLD.total_expenses
                        OR NEW.total_other_sales IS DISTINCT FROM OLD.total_other_sales
                        OR NEW.total_borrowed_items IS DISTINCT FROM OLD.total_borrowed_items
                        OR NEW.net_profit IS DISTINCT FROM OLD.net_profit
                        OR NEW.total_repayments_received IS DISTINCT FROM OLD.total_repayments_received
                        OR NEW.tithe_rate_snapshot IS DISTINCT FROM OLD.tithe_rate_snapshot
                        OR NEW.tithe_amount IS DISTINCT FROM OLD.tithe_amount
                        OR NEW.offering_amount IS DISTINCT FROM OLD.offering_amount
                        OR NEW.company_id IS DISTINCT FROM OLD.company_id
                        OR NEW.created_at IS DISTINCT FROM OLD.created_at
                        OR NEW.finalized_at IS DISTINCT FROM OLD.finalized_at
                    THEN
                        RAISE EXCEPTION
                            'remittance id=% is FINALIZED; financial fields are immutable',
                            OLD.id;
                    END IF;
                END IF;

                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="""
            CREATE OR REPLACE FUNCTION fn_lock_finalized_remittance()
            RETURNS TRIGGER AS $$
            BEGIN
                IF OLD.status = 'FINALIZED' THEN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION
                            'remittance id=% is FINALIZED and cannot be deleted',
                            OLD.id;
                    END IF;

                    IF NEW.status <> 'FINALIZED' THEN
                        RAISE EXCEPTION
                            'remittance id=% is FINALIZED; status cannot be reverted',
                            OLD.id;
                    END IF;

                    IF NEW.date IS DISTINCT FROM OLD.date
                        OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
                        OR NEW.finalized_by_id IS DISTINCT FROM OLD.finalized_by_id
                        OR NEW.total_sales IS DISTINCT FROM OLD.total_sales
                        OR NEW.total_credit_sales IS DISTINCT FROM OLD.total_credit_sales
                        OR NEW.total_commission IS DISTINCT FROM OLD.total_commission
                        OR NEW.total_salary IS DISTINCT FROM OLD.total_salary
                        OR NEW.total_expenses IS DISTINCT FROM OLD.total_expenses
                        OR NEW.total_other_sales IS DISTINCT FROM OLD.total_other_sales
                        OR NEW.total_borrowed_items IS DISTINCT FROM OLD.total_borrowed_items
                        OR NEW.net_profit IS DISTINCT FROM OLD.net_profit
                        OR NEW.total_repayments_received IS DISTINCT FROM OLD.total_repayments_received
                        OR NEW.tithe_rate_snapshot IS DISTINCT FROM OLD.tithe_rate_snapshot
                        OR NEW.tithe_amount IS DISTINCT FROM OLD.tithe_amount
                        OR NEW.offering_amount IS DISTINCT FROM OLD.offering_amount
                        OR NEW.notes IS DISTINCT FROM OLD.notes
                        OR NEW.company_id IS DISTINCT FROM OLD.company_id
                        OR NEW.created_at IS DISTINCT FROM OLD.created_at
                        OR NEW.finalized_at IS DISTINCT FROM OLD.finalized_at
                    THEN
                        RAISE EXCEPTION
                            'remittance id=% is FINALIZED; financial fields are immutable',
                            OLD.id;
                    END IF;
                END IF;

                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
        ),
    ]
