# Generated by Django 6.0.7 on 2026-08-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0011_remove_remittance_notes_remove_ridercredit_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name_plural': 'expenses'},
        ),
        migrations.AlterModelOptions(
            name='remittance',
            options={'verbose_name_plural': 'remittances'},
        ),
        migrations.AlterModelOptions(
            name='remittancerider',
            options={'verbose_name_plural': 'remittance riders'},
        ),
        migrations.AlterModelOptions(
            name='remittanceriderproductline',
            options={'verbose_name_plural': 'remittance rider product lines'},
        ),
        migrations.AlterModelOptions(
            name='remittancestaff',
            options={'verbose_name_plural': 'remittance staff'},
        ),
        migrations.AlterModelOptions(
            name='ridercredit',
            options={'verbose_name_plural': 'rider credits'},
        ),
        migrations.AlterModelOptions(
            name='ridercreditrepayment',
            options={'verbose_name_plural': 'rider credit repayments'},
        ),
        migrations.AlterModelOptions(
            name='riderdeduction',
            options={'verbose_name_plural': 'rider deductions'},
        ),
        migrations.AlterModelOptions(
            name='staffdeduction',
            options={'verbose_name_plural': 'staff deductions'},
        ),
    ]
