# Generated by Django 6.0.7 on 2026-08-17 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0012_alter_expense_options_alter_remittance_options_and_more'),
        ('settings', '0003_seed_jps2_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='remittance',
            name='unique_remittance_company_date',
        ),
        migrations.AddConstraint(
            model_name='remittance',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'date'), name='unique_remittance_company_date'),
        ),
        migrations.AddConstraint(
            model_name='remittance',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('date',), name='unique_remittance_null_company_date'),
        ),
    ]
