# Generated by Django 6.0.7 on 2026-08-19 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_company_alter_systemconfig_company'),
        ('remittance', '0013_remove_remittance_unique_remittance_company_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.company'),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='core.company'),
        ),
        migrations.AlterField(
            model_name='remittancerider',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_riders', to='core.company'),
        ),
        migrations.AlterField(
            model_name='remittanceriderproductline',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_rider_product_lines', to='core.company'),
        ),
        migrations.AlterField(
            model_name='remittancestaff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_staff', to='core.company'),
        ),
        migrations.AlterField(
            model_name='ridercredit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_credits', to='core.company'),
        ),
        migrations.AlterField(
            model_name='ridercreditrepayment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_credit_repayments', to='core.company'),
        ),
        migrations.AlterField(
            model_name='riderdeduction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_deductions', to='core.company'),
        ),
        migrations.AlterField(
            model_name='staffdeduction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_deductions', to='core.company'),
        ),
    ]
