# Generated by Django 6.0.7 on 2026-10-08 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0013_remove_remittance_unique_remittance_company_date_and_more'),
        ('settings', '0003_seed_jps2_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='remittance_staff',
            field=models.ForeignKey(blank=True, help_text='When set, this expense is attributed to a specific staff member.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='remittance.remittancestaff'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'remittance_staff'], name='remittance__company_b324f7_idx'),
        ),
    ]
