# Generated by Django 6.0.7 on 2026-10-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0014_expense_remittance_staff_and_more'),
        ('settings', '0003_seed_jps2_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='remittancerider',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_riders', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='remittanceriderproductline',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_rider_product_lines', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='remittancestaff',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_staff', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='ridercredit',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_credits', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='ridercreditrepayment',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_credit_repayments', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='riderdeduction',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_deductions', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='staffdeduction',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_deductions', to='settings.company'),
        ),
    ]
