# Generated by Django 6.0.7 on 2026-08-01 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('remittance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditline',
            name='remittance_rider_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_lines', to='remittance.remittanceriderproductline'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='credit_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.creditline'),
        ),
    ]
