# Generated by Django 6.0.7 on 2026-08-01 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('remittance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to='remittance.remittance'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['debt_balance'], name='customers_c_debt_ba_cb4ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_credit_at'], name='customers_c_last_cr_c62445_idx'),
        ),
        migrations.AddField(
            model_name='creditline',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_lines', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['credit_line'], name='customers_c_credit__33d194_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['remittance'], name='customers_c_remitta_393415_idx'),
        ),
    ]
