# Generated by Django 6.0.7 on 2026-08-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditpayment',
            new_name='customers_c_credit__50d466_idx',
            old_name='customers_c_credit__33d194_idx',
        ),
        migrations.RenameIndex(
            model_name='creditpayment',
            new_name='customers_c_remitta_6a203f_idx',
            old_name='customers_c_remitta_393415_idx',
        ),
        migrations.AlterModelTable(
            name='creditline',
            table='customers_credit_line',
        ),
        migrations.AlterModelTable(
            name='creditpayment',
            table='customers_credit_payment',
        ),
    ]
