# Generated by Django 6.0.7 on 2026-08-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_customers_c_credit__33d194_idx_customers_c_credit__50d466_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='flagged_reason',
            field=models.CharField(blank=True, help_text='Human-readable reason set when status becomes FLAGGED/BLACKLISTED.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged (Anomalous)'), ('blacklisted', 'Blacklisted')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='customers_c_status_ce44cf_idx'),
        ),
    ]
