# Generated by Django 6.0.7 on 2026-08-12 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_customer_notes'),
        ('remittance', '0003_rename_remittance__remitta_6fe674_idx_remittance__remitta_a1d3f2_idx_and_more'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='creditpayment',
            name='customers_c_credit__50d466_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditpayment',
            name='customers_c_remitta_6a203f_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_debt_ba_cb4ca0_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_last_cr_c62445_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_status_ce44cf_idx',
        ),
        migrations.AddField(
            model_name='creditline',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_lines', to='settings.company'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_payments', to='settings.company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='settings.company'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['company', 'credit_line'], name='customers_c_company_12eb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['company', 'remittance'], name='customers_c_company_c24c83_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'debt_balance'], name='customers_c_company_656215_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'last_credit_at'], name='customers_c_company_452f42_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'status'], name='customers_c_company_64b649_idx'),
        ),
    ]
