# Generated by Django 6.0.7 on 2026-08-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_creditpayment_customers_c_credit__50d466_idx_and_more'),
        ('remittance', '0004_remove_expense_remittance__remitta_2c0d46_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='remittance_rider_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_lines', to='remittance.remittanceriderproductline'),
        ),
    ]
