# Generated by Django 6.0.7 on 2026-08-12 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_credit_limit_and_more'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditline',
            name='care_of',
            field=models.ForeignKey(blank=True, help_text='User responsible for extending this credit (admin/staff/driver).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_lines_care_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BorrowedContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_key', models.CharField(choices=[('round_8gal', 'Round 8gal'), ('slim_8gal', 'Slim 8gal'), ('other', 'Other')], max_length=20)),
                ('qty_borrowed', models.SmallIntegerField()),
                ('qty_returned', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_of', models.ForeignKey(blank=True, help_text='User responsible for lending these containers (admin/staff/driver).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_containers_care_of', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_containers', to='settings.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_containers', to='customers.customer')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this borrowing entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_borrowed_containers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_borrowed_container',
                'indexes': [models.Index(fields=['company', 'customer'], name='customers_b_company_bbb56c_idx'), models.Index(fields=['company', 'care_of'], name='customers_b_company_dbab54_idx')],
            },
        ),
    ]
