# Generated by Django 6.0.7 on 2026-08-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_creditpayment_remittance_nullable'),
        ('remittance', '0005_lock_finalized_remittance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpayment',
            name='remittance',
            field=models.ForeignKey(blank=True, help_text='The rider remittance this payment was collected through, if any. Null for counter collections recorded via the Collect modal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to='remittance.remittance'),
        ),
    ]
