# Generated by Django 6.0.7 on 2026-08-14 08:34

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_overdue_threshold_days'),
        ('customers', '0011_alter_creditpayment_remittance'),
        ('remittance', '0009_remove_total_rider_credits_update_trigger'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedcontainer',
            name='qty_borrowed',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='borrowedcontainer',
            name='qty_returned',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='qty_credited',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='qty_remaining',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='total_credit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='unit_price_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='containers_paid',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='borrowed_other',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='borrowed_round_8gal',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='borrowed_slim_8gal',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='debt_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='creditline',
            index=models.Index(fields=['customer', 'qty_remaining'], name='customers_c_custome_05dc7c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'deleted_at'], name='customers_c_company_0ac6cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='borrowedcontainer',
            constraint=models.CheckConstraint(condition=models.Q(('qty_returned__gte', 0)), name='borrowed_qty_returned_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='borrowedcontainer',
            constraint=models.CheckConstraint(condition=models.Q(('qty_returned__lte', models.F('qty_borrowed'))), name='borrowed_qty_returned_not_exceeds_borrowed'),
        ),
        migrations.AddConstraint(
            model_name='creditline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_remaining__gte', 0)), name='credit_line_qty_remaining_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='creditline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_remaining__lte', models.F('qty_credited'))), name='credit_line_qty_remaining_not_exceeds_credited'),
        ),
        migrations.AddConstraint(
            model_name='creditpayment',
            constraint=models.CheckConstraint(condition=models.Q(('containers_paid__gte', 0)), name='credit_payment_containers_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='creditpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='credit_payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('debt_balance__gte', 0)), name='customer_debt_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__gte', 0)), name='customer_credit_limit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('borrowed_round_8gal__gte', 0)), name='customer_borrowed_round_8gal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('borrowed_slim_8gal__gte', 0)), name='customer_borrowed_slim_8gal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('borrowed_other__gte', 0)), name='customer_borrowed_other_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('company', 'name'), name='unique_active_customer_name_per_company'),
        ),
    ]
