# Generated by Django 6.0.7 on 2026-08-14 14:12

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_overdue_threshold_days'),
        ('customers', '0012_alter_borrowedcontainer_qty_borrowed_and_more'),
        ('remittance', '0009_remove_total_rider_credits_update_trigger'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedcontainer',
            name='transaction_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Date the containers were actually lent (may be backdated for backlog).'),
        ),
        migrations.AddField(
            model_name='creditline',
            name='transaction_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Date the credit was actually extended (may be backdated for backlog).'),
        ),
        migrations.AddIndex(
            model_name='borrowedcontainer',
            index=models.Index(fields=['company', 'transaction_date'], name='customers_b_company_907790_idx'),
        ),
        migrations.AddIndex(
            model_name='creditline',
            index=models.Index(fields=['company', 'transaction_date'], name='customers_c_company_e9af8d_idx'),
        ),
    ]
