# Generated by Django 6.0.7 on 2026-08-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_borrowedcontainer_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowedcontainer',
            options={'verbose_name_plural': 'borrowed containers'},
        ),
        migrations.AlterModelOptions(
            name='creditline',
            options={'verbose_name_plural': 'credit lines'},
        ),
        migrations.AlterModelOptions(
            name='creditpayment',
            options={'verbose_name_plural': 'credit payments'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customers'},
        ),
        migrations.AddField(
            model_name='borrowedcontainer',
            name='returned_at',
            field=models.DateField(blank=True, db_index=True, help_text='Date the most recent return was recorded (may be backdated).', null=True),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='paid_at',
            field=models.DateField(blank=True, db_index=True, help_text='Date the payment was made (may be backdated for past collections).', null=True),
        ),
    ]
