# Generated by Django 6.0.7 on 2026-08-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_borrowedcontainer_options_and_more'),
        ('settings', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['deleted_at'], name='idx_customer_active'),
        ),
    ]
