# Generated by Django 6.0.7 on 2026-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_customer_idx_customer_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditline',
            index=models.Index(condition=models.Q(('qty_remaining__gt', 0)), fields=['company', 'care_of'], name='credit_line_open_by_care_of'),
        ),
    ]
