# Generated by Django 6.0.7 on 2026-08-30 05:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_creditline_remittance(apps, schema_editor):
    """Link existing CreditLine records to the remittance on the same transaction_date."""
    CreditLine = apps.get_model('customers', 'CreditLine')
    Remittance = apps.get_model('remittance', 'Remittance')

    for credit in CreditLine.objects.filter(remittance__isnull=True).iterator():
        try:
            remittance = Remittance.objects.get(
                company=credit.company,
                date=credit.transaction_date,
            )
        except Remittance.DoesNotExist:
            continue

        credit.remittance = remittance
        credit.save(update_fields=['remittance'])


def reverse_backfill(apps, schema_editor):
    """Clear the remittance FK on reversal."""
    CreditLine = apps.get_model('customers', 'CreditLine')
    CreditLine.objects.update(remittance=None)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_credit_line_open_by_care_of_idx'),
        ('remittance', '0013_remove_remittance_unique_remittance_company_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditline',
            name='remittance',
            field=models.ForeignKey(blank=True, help_text='The remittance on which this credit was originally reported in sales.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_credit_lines', to='remittance.remittance'),
        ),
        migrations.RunPython(backfill_creditline_remittance, reverse_backfill),
    ]
