# Generated by Django 6.0.7 on 2026-08-19 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_company_alter_systemconfig_company'),
        ('customers', '0016_credit_line_open_by_care_of_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedcontainer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_containers', to='core.company'),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_lines', to='core.company'),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_payments', to='core.company'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company'),
        ),
    ]
