# Generated by Django 6.0.7 on 2026-10-08 07:44

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_options_alter_systemconfig_options'),
        ('customers', '0017_creditline_remittance'),
        ('remittance', '0014_expense_remittance_staff_and_more'),
        ('settings', '0003_seed_jps2_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='borrowedcontainer',
            index=models.Index(fields=['customer', '-created_at'], name='idx_borrowed_cust_created'),
        ),
        migrations.AddIndex(
            model_name='borrowedcontainer',
            index=models.Index(condition=models.Q(('qty_returned__lt', models.F('qty_borrowed'))), fields=['company', 'care_of'], name='idx_borrowed_open_by_care_of'),
        ),
        migrations.AddIndex(
            model_name='creditline',
            index=models.Index(fields=['customer', '-created_at'], name='idx_creditline_cust_created'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['credit_line', '-created_at'], name='idx_payment_cl_created'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['company', 'paid_at'], name='idx_payment_company_paid_at'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('debt_balance__gt', 0), ('deleted_at__isnull', True)), fields=['company', 'debt_balance'], name='idx_customer_active_debtors'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('name', name='gin_trgm_ops'), condition=models.Q(('deleted_at__isnull', True)), name='idx_customer_name_trgm'),
        ),
    ]
