# Generated by Django 6.0.7 on 2026-10-08 08:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_borrowedcontainer_idx_borrowed_cust_created_and_more'),
        ('settings', '0003_seed_jps2_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedcontainer',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_containers', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='borrowedcontainer',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date the containers were actually lent (may be backdated for backlog).'),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_lines', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='creditline',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date the credit was actually extended (may be backdated for backlog).'),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_payments', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='paid_at',
            field=models.DateField(blank=True, help_text='Date the payment was made (may be backdated for past collections).', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='settings.company'),
        ),
    ]
