# Generated by Django 6.0.7 on 2026-08-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
