# Generated by Django 6.0.7 on 2026-08-12 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_auditlog'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WATER', 'Water'), ('CONTAINER', 'Container'), ('OTHERS', 'Others')], default='OTHERS', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='settings.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_configs', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deactivated_at__isnull', True)), fields=('company', 'name', 'variation'), name='unique_product_company_name_variation'),
        ),
        migrations.AddConstraint(
            model_name='systemconfig',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_systemconfig_company_key'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
