# Generated by Django 6.0.7 on 2026-08-12 02:04

from django.db import migrations, models


_DEFAULT_PRODUCT_NAMES_VARIATIONS = [
    ("Alkaline Water", "5-Gallon Round"),
    ("Mineral Water", "5-Gallon Slim"),
    ("Purified Drinking Water", "1-Gallon Dispenser"),
    ("Pet Bottles", "350ml Case (24 Pcs)"),
]


def mark_default_products(apps, schema_editor):
    """Back-fills ``is_default=True`` on the seeded core product catalogue.

    Matches by (name, variation) so the back-fill is independent of pk
    assignment.  Only rows that are not yet soft-deleted are updated.
    """
    Product = apps.get_model('core', 'Product')
    for name, variation in _DEFAULT_PRODUCT_NAMES_VARIATIONS:
        Product.objects.filter(
            name__iexact=name,
            variation__iexact=variation,
            deleted_at__isnull=True,
        ).update(is_default=True)


def unmark_default_products(apps, schema_editor):
    """Reverse: clears ``is_default`` on any rows we may have set."""
    Product = apps.get_model('core', 'Product')
    for name, variation in _DEFAULT_PRODUCT_NAMES_VARIATIONS:
        Product.objects.filter(
            name__iexact=name,
            variation__iexact=variation,
        ).update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_systemconfig_defaults'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_company_name_variation',
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks system-default products locked from edits and deletion.'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'deleted_at'], name='core_produc_company_9198ae_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'deactivated_at'], name='core_produc_company_982cef_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deactivated_at__isnull', True), ('deleted_at__isnull', True)), fields=('company', 'name', 'variation'), name='unique_product_company_name_variation'),
        ),
        migrations.RunPython(mark_default_products, unmark_default_products),
    ]
