# Generated by Django 6.0.7 on 2026-08-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0009_seed_overdue_threshold_days'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "core_produc_company_8398c1_idx" ON "core_product" ("company_id", "is_default", "name", "variation");',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "core_produc_company_8398c1_idx";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='product',
                    index=models.Index(fields=['company', 'is_default', 'name', 'variation'], name='core_produc_company_8398c1_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "core_system_key_c61b2f_idx" ON "core_system_config" ("key", "company_id");',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "core_system_key_c61b2f_idx";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='systemconfig',
                    index=models.Index(fields=['key', 'company'], name='core_system_key_c61b2f_idx'),
                ),
            ],
        ),
    ]
