# Generated by Django 6.0.7 on 2026-08-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_core_produc_company_8398c1_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': 'system config', 'verbose_name_plural': 'system configs'},
        ),
    ]
