# Generated by Django 6.0.7 on 2026-10-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_options_alter_systemconfig_options'),
        ('settings', '0003_seed_jps2_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_configs', to='settings.company'),
        ),
    ]
