# Generated by Django 6.0.7 on 2026-08-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailysnapshot',
            table='analytics_daily_snapshot',
        ),
    ]
