# Generated by Django 6.0.7 on 2026-08-12 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_dailysnapshot_table'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysnapshot',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='settings.company'),
        ),
        migrations.AddField(
            model_name='dailysnapshot',
            name='offering_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailysnapshot',
            name='snapshot_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='dailysnapshot',
            constraint=models.UniqueConstraint(fields=('company', 'snapshot_date'), name='unique_dailysnapshot_company_date'),
        ),
    ]
