# Generated by Django 6.0.7 on 2026-08-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_dailysnapshot_company_dailysnapshot_offering_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailysnapshot',
            name='unique_dailysnapshot_company_date',
        ),
        migrations.DeleteModel(
            name='DailySnapshot',
        ),
    ]
