# Generated by Django 6.0.7 on 2026-08-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_restrict_delete_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='role',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
