# Generated by Django 6.0.7 on 2026-08-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_status_user_deactivated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRefreshToken',
        ),
    ]
