# Generated by Django 6.0.7 on 2026-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_userrefreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='When True, the user must change their password on next login.'),
        ),
    ]
