# Generated by Django 6.0.7 on 2026-08-12 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_unique_together_product_category_and_more'),
        ('settings', '0001_initial'),
        ('users', '0006_force_password_change'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drivercommission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='drivercommission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_commissions', to='settings.company'),
        ),
        migrations.AddField(
            model_name='role',
            name='company',
            field=models.ForeignKey(blank=True, help_text='NULL = platform-default role template shared across tenants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='settings.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='NULL = platform superuser (sees all tenants).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='settings.company'),
        ),
        migrations.AddConstraint(
            model_name='drivercommission',
            constraint=models.UniqueConstraint(fields=('company', 'driver', 'product'), name='unique_driver_commission_company_driver_product'),
        ),
    ]
