# Generated by Devin

from django.db import migrations

MODULES = ["Remittance", "Customers", "Products", "Users", "Reports"]

CANONICAL_ROLES = {
    "Admin": "Full access to all modules and operations.",
    "Staff": "Read, write, and update access to Remittance, Customers, and Products.",
    "Driver": "No access to back-office modules.",
}


def _all_permissions():
    return {
        module: {
            "can_read": True,
            "can_write": True,
            "can_update": True,
            "can_delete": True,
        }
        for module in MODULES
    }


def _staff_permissions():
    return {
        **{
            module: {
                "can_read": True,
                "can_write": True,
                "can_update": True,
                "can_delete": False,
            }
            for module in ["Remittance", "Customers", "Products"]
        },
        **{
            module: {
                "can_read": False,
                "can_write": False,
                "can_update": False,
                "can_delete": False,
            }
            for module in ["Users", "Reports"]
        },
    }


def _none_permissions():
    return {
        module: {
            "can_read": False,
            "can_write": False,
            "can_update": False,
            "can_delete": False,
        }
        for module in MODULES
    }


PERMISSIONS = {
    "Admin": _all_permissions(),
    "Staff": _staff_permissions(),
    "Driver": _none_permissions(),
}


def _canonicalize_roles(apps):
    """Renames/merges existing case-insensitive duplicates into the canonical set."""
    Role = apps.get_model("users", "Role")
    for canonical in CANONICAL_ROLES:
        candidates = list(Role.objects.filter(name__iexact=canonical))
        if not candidates:
            continue
        # Prefer the exact-cased canonical row, then the oldest one.
        candidates.sort(key=lambda r: (0 if r.name == canonical else 1, r.id))
        keeper = candidates[0]
        keeper.name = canonical
        keeper.description = CANONICAL_ROLES[canonical]
        keeper.is_default = True
        keeper.company_id = None
        keeper.deleted_at = None
        keeper.save(
            update_fields=[
                "name",
                "description",
                "is_default",
                "company_id",
                "deleted_at",
            ]
        )
        for extra in candidates[1:]:
            extra.is_default = False
            extra.save(update_fields=["is_default"])
            extra.delete()


def _create_default_roles_and_permissions(apps, schema_editor):
    _canonicalize_roles(apps)
    Role = apps.get_model("users", "Role")
    Permission = apps.get_model("users", "Permission")

    for role_name, description in CANONICAL_ROLES.items():
        role, _ = Role.objects.update_or_create(
            name=role_name,
            defaults={
                "description": description,
                "is_default": True,
                "company_id": None,
                "deleted_at": None,
            },
        )
        for action, flags in PERMISSIONS[role_name].items():
            Permission.objects.update_or_create(
                role=role,
                action=action,
                defaults=flags,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_drivercommission_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(
            _create_default_roles_and_permissions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
