# Generated by Django 6.0.7 on 2026-08-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_default_roles_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_expires_at',
            field=models.DateTimeField(blank=True, help_text="Date after which the user's password is considered expired.", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_expires_at',
            field=models.DateTimeField(blank=True, help_text="Date after which the user's PIN is considered expired.", null=True),
        ),
    ]
