# Generated by Django 6.0.7 on 2026-08-14 03:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_permission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Fixed daily salary rate for Staff role users. Drivers are commission-based.', max_digits=10, null=True),
        ),
    ]
