# Generated by Django 6.0.7 on 2026-08-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('settings', '0001_initial'),
        ('users', '0011_user_daily_rate'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "users_user_company_f4b92f_idx" ON "users_user" ("company_id", "deleted_at", "deactivated_at", "is_active");',
                    reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "users_user_company_f4b92f_idx";',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='user',
                    index=models.Index(fields=['company', 'deleted_at', 'deactivated_at', 'is_active'], name='users_user_company_f4b92f_idx'),
                ),
            ],
        ),
    ]
