# Generated by Django 6.0.7 on 2026-08-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_core_produc_company_8398c1_idx_and_more'),
        ('settings', '0001_initial'),
        ('users', '0012_user_users_user_company_f4b92f_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='drivercommission',
            index=models.Index(fields=['company', 'driver', 'product'], name='users_drive_company_cfc064_idx'),
        ),
        migrations.AddIndex(
            model_name='drivercommission',
            index=models.Index(fields=['company', 'product'], name='users_drive_company_cff58f_idx'),
        ),
    ]
