# Generated by Django 6.0.7 on 2026-08-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_company_options'),
        ('users', '0013_drivercommission_users_drive_company_cfc064_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivercommission',
            options={'verbose_name_plural': 'driver commissions'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': 'permissions'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True), ('deleted_at__isnull', True)), fields=('name',), name='unique_default_role_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('deleted_at__isnull', True)), fields=('company', 'name'), name='unique_tenant_role_name'),
        ),
    ]
