# Generated by Django 6.0.7 on 2026-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('settings', '0003_seed_jps2_company'),
        ('users', '0014_alter_drivercommission_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', 'deleted_at'], name='idx_user_company_active'),
        ),
    ]
