# Generated by Django 6.0.7 on 2026-08-19 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_company_alter_systemconfig_company'),
        ('users', '0014_alter_drivercommission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercommission',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_commissions', to='core.company'),
        ),
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(blank=True, help_text='NULL = platform-default role template shared across tenants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='NULL = platform superuser (sees all tenants).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company'),
        ),
    ]
