# Generated by Django 6.0.7 on 2026-10-08 07:44

import django.db.models.functions.text
from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('settings', '0003_seed_jps2_company'),
        ('users', '0015_user_idx_user_company_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.TenantUserManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Lower('username'), name='idx_user_lower_username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Lower('email'), name='idx_user_lower_email'),
        ),
    ]
