# Generated by Django 6.0.7 on 2026-10-08 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_seed_jps2_company'),
        ('users', '0016_alter_user_managers_user_idx_user_lower_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercommission',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_commissions', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, help_text='NULL = platform-default role template shared across tenants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, db_index=False, help_text='NULL = platform superuser (sees all tenants).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='settings.company'),
        ),
    ]
